### ISSUE TITLE
Layout issue on iOS

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/csh-calendar-2#3]
There is a one pixel grey line that is included in your header the breaks the visual aesthetic of Safari on iOS 15.

![one pixel gray line](https://cdn-std.droplr.net/files/acc_60763/evPGoh)

**Comment by dax-dot-gay** [comment]
I have no way to test fixes to this, if you know a way to emulate iOS on Arch I'd be happy to hear it tho

**Comment by WillNilges** [comment]
https://github.com/mbillow

**Comment by Lontronix** [comment]
@iTecAI did you fix this? I'm not seeing it

**Comment by dax-dot-gay** [comment]
I didn't fix this, I don't know what to look for on mbillow's repos so I still can't test fixes

**Comment by mbillow** [comment]
Playing around with it, it looks to be the browser adding this and not the project. Closing this for now since I doubt there is anything we can do here.
