### ISSUE TITLE
Add forward/back buttons for month

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/csh-calendar-2#5]
I find I get much more utility out of a forward/back button setup on a calendar than I do a dropdown. Give me the `CHEVRON_LEFT` please!

**Comment by dax-dot-gay** [comment]
boi
these exist
theyre the big left/right chevrons on the left and right sides of the page
or if ur on mobile on the bottom of the page

**Comment by WillNilges** [comment]
🤡 _hjonk_
